version: "3.8"
services:
  flask-app:
    build: ./flask-app
    ports:
      - "5000:5000"
    networks:
      - microservices
    depends_on:
      - mongo-db
      - aspnet-app
  mongo-db:
    build: ./mongo-db
    ports:
      - "27017:27017"
    networks:
      - microservices
    volumes:
      - mongo-data:/data/db
  aspnet-app:
    build: ./aspnet-app
    ports:
      - "8000:80" # asp.net core image listens on port 80
    # - "to:from"
    networks:
      - microservices
    environment:
      - "DOTNET_ENVIRONMENT=${ENV}"

volumes:
  mongo-data:

networks:
  microservices: